### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by M-Zuber** [TycheOrg/Tyche#4]
@balexandre commented on [Wed Mar 02 2016](https://github.com/TycheOrg/Home/issues/3)

from NuGet output

> Could not install package 'Tyche 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

---

@M-Zuber commented on [Wed Mar 02 2016](https://github.com/TycheOrg/Home/issues/3#issuecomment-191287770)

Thank you for reporting it. I will try and look into it this evening. Bug me here or in the gitter room if I take too long to respond

**Comment by M-Zuber** [comment]
[Here you go](https://www.nuget.org/packages/Tyche/1.1.0) @balexandre 

Thank you again for reporting this.

**Comment by balexandre** [comment]
great... 

you need to start referencing the issues in your commits, so here in this issue the fix appears.

[Here's how](http://stackoverflow.com/a/6742691/28004) you can accomplish that :)

**Comment by M-Zuber** [comment]
oops...
I usually reference in a PR and not individual commits (due to issues when rebasing), but this time I slipped up.
